# Generated by Django 4.0.5 on 2022-06-12 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0002_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
