# Generated by Django 4.0.5 on 2022-06-06 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0002_purchaseorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_quantity', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(help_text='Select the products for this sale', null=True, on_delete=django.db.models.deletion.SET_NULL, to='shoppingcart.product')),
            ],
        ),
    ]
